name: .NET build and test

on:
  pull_request:
  push:
    # branches:
    #   - main
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKDIR: "src"
      CONFIG: "TODO"
      AZURE_FUNCTIONAPP_NAME: "Func10-Hello-World"
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build a project
      run: dotnet build --configuration Release --no-restore
    - name: Test a project
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: |
        dotnet publish -c Release
      working-directory: ${{env.WORKDIR}}/HelloWorld
      shell: bash
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.7
      with:
        app-name: workshop-function-10
        package: src/HelloWorld
        publish-profile: ${{ secrets.AZURE_CREDENTIAL_CAESAR }}