name: .NET

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKDIR: "../src"
      CONFIG: "TODO"
      AZURE_FUNCTIONAPP_NAME: "Func10-Hello-World"
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0

    - name: Build a project
      run: dotnet build --configuration Release --no-restore
    - name: Test a project
      run: dotnet test --no-restore --verbosity normal
      

        

